In [2]:
import pandas as pd

df = pd.read_csv('../../data/cuisines_cleaned.csv')
df.head()

,Unnamed: 0,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,...,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini,cuisine
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,indian
1,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,indian
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,indian
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,indian
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,indian

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix,classification_report, precision_recall_curve
from sklearn.svm import SVC
import numpy as np

In [4]:
label_df = df['cuisine']
label_df.head()

0    indian
1    indian
2    indian
3    indian
4    indian
Name: cuisine, dtype: str

In [5]:
feature_df = df.drop(['Unnamed: 0', 'cuisine'], axis=1)
feature_df.head()

,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,artichoke,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [6]:
x_train, x_test, y_train, y_test = train_test_split(feature_df, label_df, test_size=0.33)

In [9]:
lr = LogisticRegression()
model = lr.fit(x_train, np.ravel(y_train))

accuracy = model.score(x_test, y_test)
print(f"Accuracy is {accuracy}")

Accuracy is 0.7831690674753601

In [10]:
print(f'ingredients: {x_test.iloc[50][x_test.iloc[50]!=0].keys()}')
print(f'cuisine: {y_test.iloc[50]}')

ingredients: Index(['brown_rice', 'kelp', 'sesame_oil', 'shiitake', 'soy_sauce',
       'vegetable_oil', 'vinegar'],
      dtype='str')
cuisine: japanese

In [11]:
test= x_test.iloc[50].values.reshape(-1, 1).T
proba = model.predict_proba(test)
classes = model.classes_
resultdf = pd.DataFrame(data=proba, columns=classes)

topPrediction = resultdf.T.sort_values(by=[0], ascending = [False])
topPrediction.head()

/Users/izzaalfiansyah/Projects/learning/ml-beginners/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

                 0
japanese  0.713500
korean    0.222170
chinese   0.063697
thai      0.000535
indian    0.000099

In [12]:
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

     chinese       0.75      0.65      0.70       274
      indian       0.93      0.83      0.88       267
    japanese       0.70      0.78      0.74       266
      korean       0.85      0.80      0.82       259
        thai       0.72      0.86      0.79       253

    accuracy                           0.78      1319
   macro avg       0.79      0.78      0.78      1319
weighted avg       0.79      0.78      0.78      1319